### ISSUE TITLE
Check doesn't work properly

### ISSUE THREAD

**Issue by aplatkouski** [hexlet-basics/exercises-css#59]
I can't pass the test on [css/modules/box/lessons/priority][] when I use next solution:

```html
<style>
  #no-border {
    border-style: none;
  }
  .border {
    border: 1px solid red;
  }
</style>
<p class="border" id="no-border">text</p>
```

The reason is:
```sh
/usr/lib/node_modules/chai/lib/chai/assertion.js:141
      throw new AssertionError(msg, {
      ^
AssertionError: expected { Object (0, 1, ...) } to have property 'border-style' of 'none', but got 'solid'
```

But the test succeeds when I swap the id selector with the class selector:

```html
<style>
  .border {
    border: 1px solid red;
  }
  #no-border {
    border-style: none;
  }
</style>

<p class="border" id="no-border">text</p>
```

I think, the check doesn't respect the priority of the selectors. See details:

https://github.com/hexlet-basics/exercises-css/blob/6f380ba368b88fb73767a546730d688da1cab7a9/modules/40-box/80-priority/description.ru.yml#L28-L29

[css/modules/box/lessons/priority]: https://ru.code-basics.com/languages/css/modules/box/lessons/priority

**Comment by ssssank** [comment]
@Psixodelik я тут копаюсь в старом :) подскажи, ты уже переписал этот урок, в задании чётко указал порядок селекторов. Думаю, можно уже закрыть этот ишью?

**Comment by Psixodelik** [comment]
Да, думаю можно закрыть :)
