### ISSUE TITLE
All items on the list are numbered "1"

### ISSUE THREAD

**Issue by JackFresca** [hexlet-basics/exercises-css#80]
![image](https://user-images.githubusercontent.com/76950230/103912595-26f74d00-5110-11eb-8f82-5cf5a2aed848.png)
not sure wether it was intended or not

**Comment by menshikova314** [comment]
This error happens because every element of the list is written as a new `<ol>` item, so numeration starts from the very beginning.
![image](https://user-images.githubusercontent.com/60028552/112657727-49824200-8e85-11eb-8e5c-7a0f4d7de966.png)

**Comment by Psixodelik** [comment]
Здравствуйте

Подправили список. Спасибо!
