### ISSUE TITLE
Broken image in exercise with box model

### ISSUE THREAD

**Issue by eugene-volkov** [hexlet-basics/exercises-css#83]
link: https://ru.code-basics.com/languages/css/lessons/box-model

Change old  broken pic
https://mdn.mozillademos.org/files/13647/box-model-standard-small.png

on 
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model/boxmodel-(3).png

or something else similar..

**Comment by eugene-volkov** [comment]
I clear browser cache, but the image still broken.
Please, check issue again https://ru.code-basics.com/languages/css/lessons/box-model

**Comment by amshkv** [comment]
merge PR does not lead to automatic deployment
Now I will upload the changes :)

**Comment by amshkv** [comment]
Picture has been updated
